version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception_network
    depends_on:
     - wordpress
    volumes:
      - /home/guzzy/data/wordpress:/var/www/html/wordpress
    restart: always
    env_file: .env

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception_network
    volumes:
      - /home/guzzy/data/wordpress:/var/www/html/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASS}
      - WORDPRESS_DB_NAME=${DB_NAME}
    depends_on:
      - mariadb
    restart: always
    env_file: .env

  mariadb:                                                        # The database service (MariaDB).
    container_name: mariadb                                   # Names the container "mariadb" for easier reference
    build: ./requirements/mariadb                             # Builds the image from a Dockerfile located in "requirements/mariadb"
    image: mariadb
    restart: on-failure                                       # Restarts the container automatically unless explicitly stopped
    env_file:
      - .env                                              # Loads environment variables from the ".env" file
    volumes: 
      - mariadb_v:/var/lib/mysql                           # Bind the mariadb volume to the MySQL data directory in the container (Ensures the MySQL database persists across container restarts)
    networks:
      - inception_network

volumes:
  mariadb_v:
    name: mariadb_v
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/guzzy/data/mariadb
    
networks:
  inception_network:
    driver: bridge